#!/usr/bin/env bash
# installs and configures HAproxy for load balancing
sudo add-apt-repository -y ppa:vbernat/haproxy-1.5
sudo apt-get -y upgrade
sudo apt-get -y dist-upgrade
sudo apt-get -y install haproxy
sudo sed -i '21i\frontend haproxynode\n    bind *:80\n    mode http\n    default_backend backendnodes\n' /etc/haproxy/haproxy.cfg
sudo sed -i '26i\backend backendnodes\n    mode http\n    balance roundrobin\n    option forwardfor\n    http-request set-header X-Forwarded-Port %[dst_port]\n    http-request add-header X-Forwarded-Proto https if { ssl_fc }\n    option httpchk HEAD / HTTP/1.1\\r\\nHost:localhost\n    server 324-web-01 35.229.102.255:80 check\n    server 324-web-02 35.231.130.210:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
