#!/usr/bin/env bash
# script that prints "Holberton School" 10 times

i=1

while [ $i -lt 21 ]
do
	case "$i" in
	'4')
	echo "bad luck in China"
	;;
	'9')
	echo "bad luck in Japan"
	;;
	'17')
	echo "bad luck in Italy"
	;;
	*)
	echo "$i"
	;;
	esac

	(( i+=1 ))
done
