#!/usr/bin/env bash
# script that prints numbers 1 to 20

i=1

while [ $i -lt 21 ]
do
	case "$i" in
	'4')
	echo "bad luck in China"
	;;
	'9')
	echo "bad luck in Japan"
	;;
	'17')
	echo "bad luck in Italy"
	;;
	*)
	echo "$i"
	;;
	esac

	(( i+=1 ))
done
